[tool.poetry]
name = "dfint64_patch"
version = "0.0.1"
description = "Text patcher for x64 bit version of the Dwarf Fortress game"
authors = ["insolor <insolor@gmail.com>"]
license = "MIT License"

[tool.poetry.dependencies]
python = "^3.10"
click = "^8.1.7"
loguru = "^0.7.2"
peclasses = {version = "^0.4.0", source = "dfint"}

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.3"
pytest-cov = "^4.1.0"
flake8 = "^6.1.0"
black = "^23.11.0"
isort = "^5.11.5"
hypothesis = "^6.91.0"
coverage = "^7.3.2"
mypy = "^1.7.1"
refurb = "^1.24.0"
ruff = "^0.1.6"

[tool.poetry.scripts]
extract = "dfint64_patch.extract_strings.cli:main"
patch = "dfint64_patch.patch:main"
patch_charmap = "dfint64_patch.charmap.cli:main"

[[tool.poetry.source]]
name = "dfint"
url = "https://dfint.github.io/pypi-index/"
priority = "explicit"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120

[tool.isort]
profile = "black"

[tool.mypy]
ignore_missing_imports = true

[tool.ruff]
line-length = 120
select = ["E", "F", "UP"]
ignore = ["UP015"]
unfixable = ["F401"]
target-version = "py310"
