[tool.poetry]
name = "dfrus64"
version = "0.0.1"
description = "Text patcher for x64 bit version of the Dwarf Fortress game"
authors = ["insolor <insolor@gmail.com>"]
license = "MIT License"

[tool.poetry.dependencies]
python = "^3.7"
click = "^8.0.1"
peclasses = { url = "https://github.com/dfint/peclasses/releases/download/0.2.0/peclasses-0.2.0-py3-none-any.whl" }
loguru = "^0.6.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
pytest-cov = "^2.12.0"
flake8 = "^3.9.2"
black = "^22.3.0"
isort = "^5.10.1"
hypothesis = "^6.58.1"

[tool.poetry.scripts]
extract = "dfrus64.extract_strings:main"
patch = "dfrus64.patch:main"
patch_charmap = "dfrus64.charmap.cli:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120

[tool.isort]
profile = "black"
